apiVersion: v1
kind: ConfigMap
metadata:
  name: encryption-service-configmap
data:
  server.port: "8013"
  server.servlet.context-path: "/"
  spring.datasource.url: "jdbc:postgresql://db-service:5432/registry"
  spring.flyway.url: "jdbc:postgresql://db-service:5432/registry"
  egov.mdms.provider: "org.egov.enc.masterdata.provider.DBMasterDataProvider"
  spring.flyway.baseline-on-migrate: "true"
  management.endpoints.web.base-path: "/"