apiVersion: apps/v1
kind: Deployment
metadata:
  name: encryption-service-deployment
spec:
  selector:
    matchLabels:
      app: encryption-service
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: encryption-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: encryption-service-container
        image: ghcr.io/sunbird-rc/encryption-service:v2.0.1
        ports:
        - containerPort: 8013
        envFrom:
        - configMapRef:
            name: encryption-service-configmap