name: id-gen-service

image: ghcr.io/sunbird-rc/id-gen-service:v2.0.1

replica: 1

environment:
  name: id-gen-service-config

container_name: id-gen-service-container

service_name: id-gen-service-service

port_name: id-gen-service-port
port: "8088"

configMap:
  name: id-gen-service-config
  data:
    spring.datasource.url: jdbc:postgresql://db-service:5432/registry
    spring.flyway.baseline-on-migrate: "true"
    autocreate.new.seq: "true"
    idformat.from.mdms: "false"
    egov.mdms.provider: org.egov.id.masterdata.provider.DBMasterDataProvider


