apiVersion: v1
kind: Service
metadata:
  name: digilocker-certificate-api-service
spec:
  selector:
    app: digilocker-certificate-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087