apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digilocker-certificate-api-pvc
spec:
  volumeName: digilocker-certificate-api-pv
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi