apiVersion: v1
kind: PersistentVolume
metadata:
  name: digilocker-certificate-api-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /my-volume/digilocker-certificate-api