apiVersion: v1
kind: Service
metadata:
  name: public-key-service-service
spec:
  selector:
    app: public-key-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300