name: metrics

image: ghcr.io/sunbird-rc/sunbird-rc-metrics

replica: 1

environment:
  name: metrics-config

container_name: metrics-container

service_name: metrics-service

port_name: metrics-port
port: "8070"

configMap:
  name: metrics-config
  data:
    CLICK_HOUSE_URL: "clickhouse-service:9002"
    CLICKHOUSE_DATABASE: "default"
    KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
    KAFKA_METRICS_TOPIC: "events"
    REDIS_URL: "redis-service:6379"