apiVersion: v1
kind: Service
metadata:
  name: credential-schema-service
spec:
  selector:
    app: credential-schema
  type: NodePort
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333