apiVersion: apps/v1
kind: Deployment
metadata:
  name: credential-schema-deployment
spec:
  selector:
    matchLabels:
      app: credential-schema
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: credential-schema
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: fluentd-sidecar
        image: fluent/fluentd:v1.14
      - name: credential-schema-container
        image: ghcr.io/sunbird-rc/sunbird-rc-credential-schema:v2.0.1
        ports:
        - containerPort: 3333
        envFrom:
        - configMapRef:
            name: credential-schema-configmap
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "curl -f http://localhost:3333/health || exit 1"
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "curl -f http://localhost:3333/health || exit 1"
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5