apiVersion: v1
kind: ConfigMap
metadata:
  name: credential-schema-configmap
data:
  DATABASE_URL: "postgres://postgres:postgres@db-service:5432/registry"
  IDENTITY_BASE_URL: "http://identity-service:3332"
  JWKS_URI: ""
  ENABLE_AUTH: "false"