apiVersion: v1
kind: ConfigMap
metadata:
  name: credential-configmap
data:
  DATABASE_URL: "postgres://postgres:postgres@db-service:5432/registry"
  IDENTITY_BASE_URL: "http://identity-service:3332"
  SCHEMA_BASE_URL: "http://credential-schema-service:3333"
  CREDENTIAL_SERVICE_BASE_URL: "https://example.com/credentials"
  JWKS_URI: ""
  ENABLE_AUTH: "false"
  #QR_TYPE=${QR_TYPE}