apiVersion: apps/v1
kind: Deployment
metadata:
  name: credential-deployment
spec:
  selector:
    matchLabels:
      app: credential
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: credential
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: credential-container
        image: ghcr.io/sunbird-rc/sunbird-rc-credentials-service:v2.0.1
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: credential-configmap
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "curl -f http://localhost:3000/health || exit 1"
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "curl -f http://localhost:3000/health || exit 1"
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5