apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
spec:
  volumeName: registry-pv
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi