apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry
  type: NodePort
  ports:
    - name: "port1"
      protocol: TCP
      port: 8200
      targetPort: 8200