apiVersion: v1
kind: Service
metadata:
  name: context-proxy-service-service
spec:
  selector:
    app: context-proxy-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 4400
      targetPort: 4400