apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  volumeName: db-pv
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi