{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }} 
spec:
  selector:
    app: {{ .Values.name }}
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
{{- end -}}