{{- define "common.statefulset" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replica | default 1}}

  selector:
    matchLabels:
      app: {{ .Values.name }}

  serviceName: {{ .Values.service_name }}

  template:
    metadata:
      labels:
        app: {{ .Values.name }}

    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Values.container_name }}
        image: {{ .Values.image }}
        ports:
          - containerPort: {{ .Values.port }}

        envFrom:
        {{- with .Values.environment }}
        - configMapRef:
            name: {{ .name }}
        {{- end }}


        {{- if .Values.minio }}
          {{- if .Values.minio.command }}
        command:
        {{ toYaml .Values.minio.command | nindent 8 }}
          {{- end }}
        {{- end }}


        {{- if .Values.securityContext }}
        securityContext:
          runAsUser: 0
          {{- if .Values.securityContext.capabilities }}
          capabilities:
            add: {{ .Values.securityContext.capabilities.add | toJson }}
          {{- end }}
        {{- end }}


        {{- with .Values.healthcheck }}
        livenessProbe:
          exec:
            command:
              {{- toYaml .test | nindent 12 }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        {{- end }}

        {{- with .Values.healthcheck }}
        readinessProbe:
          exec:
            command:
              {{- toYaml .test | nindent 12 }}
          initialDelaySeconds: 30
          periodSeconds: {{ .interval | default 30 }}
          timeoutSeconds: {{ .timeout | default 10 }}
          failureThreshold: {{ .retries | default 3 }}
        {{- end }}

        
        volumeMounts:
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}