name: clickhouse

image: clickhouse/clickhouse-server:23.4.2.11-alpine

replica: 1

service_name: clickhouse-service

port_name: clickhouse-port
port: "9000"
container_name: clickhouse-container

healthcheck:
  test: 
    - /bin/sh
    - -c
    - "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"
  interval: 30
  timeout: 10
  retries: 3
