apiVersion: v2
name: kafka
description: A kafka Helm chart for Kubernetes

type: application
version: 1.0.0
appVersion: "1.16.0"


dependencies:
  - name: common
    version: 1.0.0 
    repository: file://../../common
