name: keycloak

image: quay.io/keycloak/keycloak:16.1.1

replica: 1

environment:
  name: keycloak-config

container_name: keycloak-container

service_name: keycloak-service

port_name: keycloak-port
port: "9990"

healthcheck:
  test: 
    - /bin/sh
    - -c
    - curl -f http://localhost:9990/ || exit 1
  interval: 30
  timeout: 10
  retries: 3

configMap:
  name: keycloak-config
  data:
    KEYCLOAK_LOGO: "https://svgshare.com/i/hCs.svg"
    DB_VENDOR: "postgres"
    DB_ADDR: "db-service.default.svc.cluster.local"
    DB_PORT: "5432"
    DB_DATABASE: "registry"
    DB_USER: "postgres"
    KEYCLOAK_USER: "admin"
    KEYCLOAK_IMPORT: "/opt/jboss/keycloak/imports/realm-export.json"
    PROXY_ADDRESS_FORWARDING: "true"
    JAVA_OPTS_APPEND: "-Dinfinispan.thread.pool.size=10"
    DB_PASSWORD: "postgres"
    KEYCLOAK_PASSWORD: "admin"


volumeMounts:
  - name: keycloak-volume
    mountPath: /opt/jboss/keycloak/imports

volumes:
  - name: keycloak-volume
    configMap:
      name: config-volume-keycloak


