apiVersion: v1
kind: Service
metadata:
  name: es-service
spec:
  selector:
    app: es
  ClusterIP: none
  ports:
    - name: "es-port1"
      protocol: "TCP"
      port: 9200
      targetPort: 9200
    - name: "es-port2"
      protocol: "TCP"
      port: 9300
      targetPort: 9300