name: encryption-service

image: ghcr.io/sunbird-rc/encryption-service:v2.0.1

replica: 1

environment:
  name: encryption-service-config

container_name: encryption-service-container

service_name: encryption-service-service

port_name: encryption-service-port
port: "8013"

configMap:
  name: encryption-service-config
  data:
    server.port: "8013"
    server.servlet.context-path: "/"
    spring.datasource.url: "jdbc:postgresql://db-service:5432/registry"
    spring.flyway.url: "jdbc:postgresql://db-service:5432/registry"
    egov.mdms.provider: "org.egov.enc.masterdata.provider.DBMasterDataProvider"
    spring.flyway.baseline-on-migrate: "true"
    management.endpoints.web.base-path: "/"


