apiVersion: v1
kind: Service
metadata:
  name: file-storage-service
spec:
  selector:
    app: file-storage
  type: NodePort
  ports:
    - name: "file-storage-port1"
      protocol: "TCP"
      port: 9000
      targetPort: 9000
    - name: "file-storage-port2"
      protocol: "TCP"
      port: 9001
      targetPort: 9001