apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
spec:
  volumeName: vault-pv
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi