apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ms-deployment
spec:
  selector:
    matchLabels:
      app: notification-ms
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: notification-ms
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: notification-ms-container
        image: ghcr.io/sunbird-rc/sunbird-rc-notification-service:v2.0.1
        ports:
        - containerPort: 8765
        envFrom:
        - configMapRef:
            name: notification-ms-configmap
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "wget -nv -t1 --spider http://localhost:8765/notification-service/v1/health || exit 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "wget -nv -t1 --spider http://localhost:8765/notification-service/v1/health || exit 1"
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 10