apiVersion: v1
kind: ConfigMap
metadata:
  name: id-gen-service-configmap
data:
  spring.datasource.url: jdbc:postgresql://db-service:5432/registry
  spring.flyway.baseline-on-migrate: "true"
  autocreate.new.seq: "true"
  idformat.from.mdms: "false"
  egov.mdms.provider: org.egov.id.masterdata.provider.DBMasterDataProvider