name: credential

image: ghcr.io/sunbird-rc/sunbird-rc-credentials-service:v2.0.1

replica: 1

environment:
  name: credential-config

container_name: credential-container

service_name: credential-service

port_name: credential-port
port: "3000"

healthcheck:
  test: 
    - sh
    - -c
    - "curl -f http://localhost:3000/health || exit 1"
  interval: 30
  timeout: 10
  retries: 3

configMap:
  name: credential-config
  data:
    DATABASE_URL: "postgres://postgres:postgres@db-service:5432/registry"
    IDENTITY_BASE_URL: "http://identity-service:3332"
    SCHEMA_BASE_URL: "http://credential-schema-service:3333"
    CREDENTIAL_SERVICE_BASE_URL: "https://example.com/credentials"
    JWKS_URI: ""
    ENABLE_AUTH: "false"

