apiVersion: v2
name: bulk-issuance
description: A bulk-issuance Helm chart for Kubernetes

type: application
version: 1.0.0
appVersion: "1.16.0"


dependencies:
  - name: common
    version: 1.0.0 
    repository: file://../../common
